// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// M_within_inv_with_gid
arma::mat M_within_inv_with_gid(const arma::mat& data, const arma::uvec& vars, arma::uvec group, arma::uvec unit, arma::uvec within);
RcppExport SEXP _mutualinf_M_within_inv_with_gid(SEXP dataSEXP, SEXP varsSEXP, SEXP groupSEXP, SEXP unitSEXP, SEXP withinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type group(groupSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type within(withinSEXP);
    rcpp_result_gen = Rcpp::wrap(M_within_inv_with_gid(data, vars, group, unit, within));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mutualinf_M_within_inv_with_gid", (DL_FUNC) &_mutualinf_M_within_inv_with_gid, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_mutualinf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
