# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

M_valuerp <- function(data, group, unit) {
    .Call(`_mutualinf_M_valuerp`, data, group, unit)
}

get_internal_data_cpp <- function(data, vars) {
    .Call(`_mutualinf_get_internal_data_cpp`, data, vars)
}

get_proportion_cpp <- function(data, within, by, total = -1) {
    .Call(`_mutualinf_get_proportion_cpp`, data, within, by, total)
}

