# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

M_within_inv_with_gid <- function(data, vars, group, unit, within) {
    .Call(`_mutualinf_M_within_inv_with_gid`, data, vars, group, unit, within)
}

